### PR TITLE
Fix inspect_pod

### LINKED ISSUE #200: Error when inspecting standalone Pods
When the user requests Liz to inspect/analyze a Pod, and this Pod is not from a Deployment or ReplicaSet, the Assistan replies with an error message originated by the MCP.

This is observable using mcp version `1.0.0`

What happens is:

- The assistant invokes the `inspect_pod` MCP function
- The function returns error when the Pod doesn't belong to a Deployement OR it has no logs available

### Screenshots

https://github.com/user-attachments/assets/dcb360fd-a791-48d4-bf0c-35e78a5f2e3d

### PR DESCRIPTION
**Pull request by torchiaf**
Fixes https://github.com/rancher/rancher-ai-agent/issues/200

`inspect_pod` now returns gracefully when ReplicaSet or Logs are missing for a pod.

### CODE REVIEW

File: pkg/toolsets/core/inspect_pod_test.go [hunk 1]
```diff
@@ -556,6 +631,92 @@ func TestInspectPod(t *testing.T) {
 			fakeDynClient: dynamicfake.NewSimpleDynamicClient(inspectPodScheme()),
 			expectedError: "no URL for rancher request",
 		},
+		"inspect pod - unable to retrieve logs": {
```
Comment (raulcabello) [inline pkg/toolsets/core/inspect_pod_test.go]: This is not testing when an error is returned when getting the logs. Not sure if that'd be easy to do. Maybe remove this test case?

Comment (torchiaf) [reply pkg/toolsets/core/inspect_pod_test.go]: Let's remove it

**Review by raulcabello — APPROVED** [review]
